# Day 08 Group Worksheet
Oct 02, 2024

If you're working on CoCalc, it's good to rename your notebook with a fun group name and to include your names below so that you can easily find it later for reference.

* Group members: 

## Task 01: Array warm-ups

**A.** Create the following 5x5 matrix where the border is filled with 1s and the inside is filled with 0s. 

I.e.,
```python
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]
```

In [0]:
# Your code here


**B.** Create the following 8x8 checkerboard pattern matrix with alternating 0s and 1s.
```python
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
```

In [0]:
# Your code here


**C.** Normalize the following array (make the values sum to 1)

In [0]:
# Your code here

import numpy as np
arr = np.array([1, 2, 3, 4])



**D.** For the array `arr` below, find the mean of each row and each column. Your answers should be:
```python
Row means: [2. 5. 8.]
Column means: [4. 5. 6.]
```

In [0]:
# Your code here

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])


## Task 02: Broken phasor?

One of the security officers has dropped her phasor and wants to know if it is still functioning correctly. Knowing that the relationship between input voltage (x) and output energy (y) should follow $y = sin(e^{x^2})$, you collect the data shown below. Write some code that will find and then print the size of the largest residual (measured-y minus expected-y) so that you can consult the user manual to determine if the phasor is functioning correctly.

In [0]:
x = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15])
y = np.array([1.376, 1.941,2.062,-0.207,0.193, -0.936,-0.3810,2.691,2.266,1.113,1.534,0.594,1.391,2.415,0.522])

# Your code here



## Task 03

You are a crew member of the Starship Enterprise. Recently, the Borg (an enemy alien race) have destroyed part of the ship’s computers, so that they only accept code in "Python". Luckily, you are the ship expert on the ancient language of "Python". The captain wants to see what you can do, and asks you to write code which takes a 9-element array of numbers, such as `a = [1, 2, 3, 4, 5, 6, 7, 8, 9]`, and splits it into three arrays of length three, then stacks the three arrays to make a matrix of 3 rows.

The resulting array should look like
```
[[1 2 3]
 [4 5 6]
 [7 8 9]]
```
Do this using at least TWO different methods. You may find the exhaustive list of array methods to be helpful: https://numpy.org/doc/stable/reference/routines.html

In [0]:
# First method here
import numpy as np
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])



In [0]:
# Second method here
import numpy as np
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])



In [0]:
# A third method if you dare (optional)
import numpy as np
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])



## Task 04: Impress the Captain!

Rewrite your code from Task 02 to allow it to work for any size starting array. If the starting array cannot be split into three equal parts, add `0`s to the end until it has enough elements so that it is a multiple of three.

Hints: `np.append` the "%" (moduluo) operator and/or `np.zeros` may be of use here.

In [0]:
# Your code here




## Task 05: The Sphinx's riddle

You've come to an impasse in the road. A sphinx is sitting in the middle of the road and it won't let you pass until you answer a riddle. Unfortunately, it is asking you a new riddle and you don't already know the answer. Fortunately, you have your laptop with you, so you can quickly program the question in python to get the answer. The riddle is: there are 100 doors, and they are all closed. You visit each door (in order) 100 times:

1. On your first pass, you toggle (change the position from open ot closed or vice versa) every door.
1. On the second pass, you toggle every 2nd door (leave the first alone, toggle the second, leave the third alone, toggle the fourth).
1. On the third pass, you toggle every 3rd door (leave the first 2 alone, toggle the third etc).
1. On the fourth pass, you toggle every 4th door, etc, until on the 100th pass you toggle only the 100th door.

At the end of all this, which doors are open? Do you recognize any pattern in the doors that are left open?

In [0]:
# Your door riddle code here


